### ISSUE TITLE
chatbot에서 API 응답 없음 관련한 에러 발생

### ISSUE THREAD

**Issue by ISCMYOO** [kookmin-sw/capstone-2024-09#11]
![image](https://github.com/kookmin-sw/capstone-2024-09/assets/61531215/d05ffdad-f4af-4d44-bba1-9c4cb53b1f3c)
위의 사진처럼 접속 시 아직까지 입력 요청에 대한 에러가 빈번히 뜨고 있습니다.
해당 오류에 대해 확인 및 수정 부탁드릴게요!

**Comment by Seo-yeong-Chae** [comment]
해당 에러는 접속 시 로딩 바를 추가하는 것으로 대체하기로 하였습니다!

**Comment by ISCMYOO** [comment]
streamlit에서 react로 변경되어서 해당 오류는 더 이상 발생하지 않습니다.
