### ISSUE TITLE
Git Package 관리 및 설정

### ISSUE THREAD

**Issue by ISCMYOO** [kookmin-sw/capstone-2024-09#15]
우리 프로젝트에서는 GHCR(Git Package)를 사용하여 Docker image를 관리하고 있다.
해당 Package를 repository에 올려야 하는데 현재 Private 설정으로 되어 있는데 docker image가 완성되면 Public으로 올리기!
![image](https://github.com/kookmin-sw/capstone-2024-09/assets/61531215/4ddbd750-c4b9-412d-9b44-0b3459d108ff)

개발 단계에서는 organization에서 관리하자.

추후 개발 완성되면 꼭 올리기

**Comment by Seo-yeong-Chae** [comment]
확인하였습니다! 수고 많으십니다

**Comment by ISCMYOO** [comment]
해당 이미지 Docker Hub에 올렸습니다
