### ISSUE TITLE
처음 서버에 서비스를 배포할 때 joblib 타입의 파일 다운받는 것을 추가하기

### ISSUE THREAD

**Issue by Seo-yeong-Chae** [kookmin-sw/capstone-2024-09#24]
처음 서버에 서비스를 배포할 때 joblib 타입의 파일(tfidfVectorizer 파일, 다층 퍼셉트론 모델(분류형 ai 모델) 파일) 다운받는 것을 자동화하도록 초기 스크립트를 추가하기

해당 모델의 경우 docker에서 같이 빌드해서 사용하면 되는데 java 환경이 필요하기에 host에서 java환경을 세팅해야 함..
이를 사용법에 명시해주자

**Comment by ISCMYOO** [comment]
joblib으로 되어 있는 모델을 docker로 같이 서버 배포를 하려고 하였지만 AWS 서버 스팩상 구동이 불가능하여 별도의 AI 서버를 구동하도록 했습니다. 따라서 해당 부분은 따로 작성할 필요 없을 것 같습니다.
